// Export individual icons so they are more accessible
export { Friends } from './Friends'
export { Watch } from './Watch'
export { Water } from './Water'
export { Scales } from './Scales'
export { Plus } from './Plus'
export { Minus } from './Minus'
export { Fitbit } from './Fitbit'
export { Cross } from './Cross'
export { Chevron } from './Chevron'
export { Cog } from './Cog'
export { GoogleIcon } from './GoogleIcon'
export { HealthKitLogo } from './HealthKit'
export { GoogleFitLogo } from './GoogleFit'
